version: 2

jobs:
  build:
    working_directory: /home/reaction

    docker:
      - image: node:7-slim

    environment:
      - DOCKER_VERSION: 17.03.1-ce
      - BUILD_DIR: /opt/styleguide
      - METEOR_ALLOW_SUPERUSER: true

    steps:
      - setup_remote_docker
      - checkout

      - run: .circleci/install.sh
      - run: .circleci/build.sh

      # deploy the build (if on a deployment branch)
      - deploy:
          name: Docker Image Deploment
          command: .circleci/deploy.sh
